# Generated by Django 4.1.7 on 2023-03-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='total_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
