# Generated by Django 4.1.7 on 2023-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_website_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='code_name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
